# Specify the language node_js, nodejs version stable 
Language: node_js 
node_js: stable
services: mongodb

before_script:
  - mongo fba-service-test --eval 'db.createUser({user:"webthinh",pwd:"thinhtruong",roles:["readWrite"]});'

branches: 
  only: 
    - master

cache: 
  directories: 
    - node_modules

before_install: 
  - npm install yarn

install: 
  - yarn

jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
    - script: yarn test
    - stage: build
      name: "Build"
      script: yarn build
    - stage: deploy
      name: "Deploy"
      script:
        - apt-get update -qq && apt-get install -y -qq sshpass
        - sshpass -V
        - export SSHPASS=Quangthinh@98
        - sshpass -e scp -o stricthostkeychecking=no -r package.json root@13.67.51.59:/usr/share/nginx/html/thinhtruong.asia/webkhoa
        - script -qc "sshpass -e ssh -o StrictHostKeyChecking=no root@13.67.51.59 'cd /usr/share/nginx/html/thinhtruong.asia/webkhoa && ls'"
