# Specify the language node_js, nodejs version stable 
Language: node_js 
node_js: stable
services: mongodb
addons:
  apt:
    packages:
    - sshpass

before_script:
  - mongo fba-service-test --eval 'db.createUser({user:"webthinh",pwd:"thinhtruong",roles:["readWrite"]});'

branches: 
  only: 
    - master

cache: 
  directories: 
    - node_modules

before_install: 
  - npm install yarn

install: 
  - yarn

jobs:
  include:
    - stage: "Tests"                
      name: "Unit Tests"            
    - script: yarn test

    - stage: build_deploy
      name: "Build and Deploy"
      script:
        - yarn build
        - sshpass -V
        - export SSHPASS=Quangthinh@98
        - sshpass -e scp -o stricthostkeychecking=no -r package.json root@13.67.51.59:/usr/share/nginx/html/thinhtruong.asia/webkhoa-back
        - sshpass -e scp -o stricthostkeychecking=no -r build/. root@13.67.51.59:/usr/share/nginx/html/thinhtruong.asia/webkhoa-back/build
        - script -qc "sshpass -e ssh -o StrictHostKeyChecking=no root@13.67.51.59 'cd /usr/share/nginx/html/thinhtruong.asia/webkhoa-back && yarn && cd build && pm2 delete webkhoa-back && pm2 start index.js --name "webkhoa-backend"'"
        
